# INI ERROR NYA KARENA MENGGUNAKAN “ ” HARUSNYA "" ATAU '' DAN PRINT P NYA GEDE HARUSNYA KECIL
print("Halo.. \n")

# INI ERROR NYA KARENA MENGGUNAKAN ” (SATU BIJI PULA), HARUSNYA "" ATAU '' DAN TANPA MENGGUNAKAN ; (DI PYTHON ; TIDAK DIPERLUKAN)
print("Selamat Datang! \n") 

# INI ERRORNYA KARENA ADA SPASI DI AWAL SEBELUM PRINT, DAN MASIH MENGGUNAKAN “ ”  
print ("Sudah makan belum? \n")

# INI ERRORNYA KARENA ADA SPASI DI AWAL SEBELUM PRINT, DAN MASIH MENGGUNAKAN “ ”  
print("Oh belum ya.. ya udah \n")